package terrain

const MAX_LOADED_REGIONS = 256

const DEFAULT_SEED = 124
const TERRAIN_PERLIN_MAX = 8
const TERRAIN_PERLIN_INCREASE = 5
const PERLIN_FREQUENCY = 128.0
const PERLIN_DILATION = 0.5 // 0.5 - 1.0

const BUILDINGS_MIN = 9
const BUILDINGS_MAX = 15

const TOWN_MIN_EDGE = 10
const TOWN_MAX_EDGE = 190
