package terrain

const MAX_LOADED_REGIONS = 256

const DEFAULT_SEED = 125
const TERRAIN_PERLIN_PERIOD = 256
const TERRAIN_PERLIN_MAX = 6
const PERLIN_FREQUENCY = 0.1
const PERLIN_DILATION = 3
const PERLIN_UPLIFT = 5

const BUILDINGS_MIN = 9
const BUILDINGS_MAX = 15

const TOWN_MIN_EDGE = 10
const TOWN_MAX_EDGE = 190
