package terrain

const MAX_LOADED_REGIONS = 256

const DEFAULT_SEED = 124
const TERRAIN_PERLIN_MAX = 8
const TERRAIN_PERLIN_INCREASE = 5
const PERLIN_FREQUENCY = 128.0

const BUILDINGS_MIN = 6
const BUILDINGS_MAX = 15
