package regions


const MAX_ENTITIES_PER_FIELD = 5
const MAX_ENTITIES_PER_DUNGEON = 4
const MAX_SOLDIERS_PER_TOWN = 3
const MIN_SOLDIERS_PER_TOWN = 1
const SOLDIER_IN_HOUSE_ODDS = 2
const TRADER_IN_HOUSE_ODDS = 4
const WOLF_ODDS = 4
const DEATH_WAKER_ODDS = 4

const ODDS_DUNGEON = 14
const ODDS_TOWN = 14
