package regions


const MAX_ENTITIES_PER_FIELD = 5
const MAX_ENTITIES_PER_DUNGEON = 4
const MAX_SOLDIERS_PER_TOWN = 3
const MIN_SOLDIERS_PER_TOWN = 1
const SOLDIER_IN_HOUSE_ODDS = 2
const TRADER_IN_HOUSE_ODDS = 4
const WOLF_ODDS = 4
const DEATH_WAKER_ODDS = 4

const ODDS_DUNGEON = 14
const ODDS_TOWN = 14

const MAX_ITEMS_PER_SHOP_CHEST = 10
const MIN_ITEMS_PER_SHOP_CHEST = 1
const ODDS_SHOP_CHEST_POTION = 2 // out of 10
const ODDS_SHOP_CHEST_SWORD = 3 // out of 10
const SHOP_CHEST_SWORD_MAX_LEV = 10
